### ISSUE TITLE
version 3.0.5 wont open

### ISSUE THREAD

**Issue by mansverychill** [dunnousername/yanderifier#18]
windows 10 pro, gtx 1050ti, intel i5 4590s

**Comment by Aidan-Lineberry** [comment]
did you run the "install" file ? you need to properly install the program before starting yanderifier

**Comment by mansverychill** [comment]
yes.

**Comment by hesa656** [comment]
This version doesn't work for me too even if i run "install" file...

in Start yanderify (super verbose debug mode)" file i have:
```
`Could not find conda environment: yanderify
You can list all discoverable environments with `conda info --envs`.


(base) C:\Users\hesam\Desktop\yanderifier-master\yanderify>python -v yanderify.py debug verbose
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__pycache__\__init__.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__init__.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\encodings\\__pycache__\\__init__.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\codecs.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\codecs.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\codecs.cpython-38.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85A970AC0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__pycache__\aliases.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\aliases.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\encodings\\__pycache__\\aliases.cpython-38.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AAEC6D0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85A9708B0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__pycache__\utf_8.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\utf_8.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\encodings\\__pycache__\\utf_8.cpython-38.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85A970940>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__pycache__\cp1250.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\cp1250.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\encodings\\__pycache__\\cp1250.cpython-38.pyc'
import 'encodings.cp1250' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AAF71C0>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\__pycache__\latin_1.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\encodings\latin_1.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\encodings\\__pycache__\\latin_1.cpython-38.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AAF7550>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\io.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\io.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\io.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\abc.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\abc.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\abc.cpython-38.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AAF79A0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AAF76D0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\site.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\site.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\site.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\os.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\os.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\os.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\stat.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\stat.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\stat.cpython-38.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB32340>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\_collections_abc.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\_collections_abc.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\_collections_abc.cpython-38.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB323D0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\ntpath.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\ntpath.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\ntpath.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\genericpath.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\genericpath.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\genericpath.cpython-38.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB54F40>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB32CD0>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB12A60>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\_sitebuiltins.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\_sitebuiltins.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\_sitebuiltins.cpython-38.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB2A5E0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\_bootlocale.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\_bootlocale.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\_bootlocale.cpython-38.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB54D90>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB12370>
Python 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
Loading...
# C:\Users\hesam\Desktop\yanderifier-master\yanderify\__pycache__\hhelper.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\yanderify\hhelper.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\yanderify\\__pycache__\\hhelper.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\datetime.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\datetime.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\datetime.cpython-38.pyc'
import 'math' # <class '_frozen_importlib.BuiltinImporter'>
import '_datetime' # <class '_frozen_importlib.BuiltinImporter'>
import 'datetime' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB8D730>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\random.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\random.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\random.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\warnings.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\warnings.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\warnings.cpython-38.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD91D30>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\bisect.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\bisect.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\bisect.cpython-38.pyc'
import '_bisect' # <class '_frozen_importlib.BuiltinImporter'>
import 'bisect' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD9F6A0>
import '_sha512' # <class '_frozen_importlib.BuiltinImporter'>
import '_random' # <class '_frozen_importlib.BuiltinImporter'>
import 'random' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB8D7C0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\getpass.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\getpass.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\getpass.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\contextlib.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\contextlib.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\contextlib.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\collections\__pycache__\__init__.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\collections\__init__.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\collections\\__pycache__\\__init__.cpython-38.pyc'
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\operator.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\operator.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\operator.cpython-38.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD31220>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\keyword.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\keyword.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\keyword.cpython-38.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD31310>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\heapq.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\heapq.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\heapq.cpython-38.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD31490>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\reprlib.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\reprlib.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\reprlib.cpython-38.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD314C0>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD7C970>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\functools.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\functools.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\functools.cpython-38.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD31FD0>
# C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\__pycache__\types.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\miniconda\lib\types.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\miniconda\\lib\\__pycache__\\types.cpython-38.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AD37760>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB9ACD0>
import 'msvcrt' # <class '_frozen_importlib.BuiltinImporter'>
import 'getpass' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB9A910>
import 'hhelper' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB8D3D0>
# C:\Users\hesam\Desktop\yanderifier-master\yanderify\__pycache__\steghelper.cpython-38.pyc matches C:\Users\hesam\Desktop\yanderifier-master\yanderify\steghelper.py
# code object from 'C:\\Users\\hesam\\Desktop\\yanderifier-master\\yanderify\\__pycache__\\steghelper.cpython-38.pyc'
import 'steghelper' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D85AB9AB50>
Traceback (most recent call last):
  File "yanderify.py", line 25, in <module>
    import matplotlib
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matplotlib'
# clear sys.audit hooks
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing winreg
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# destroy encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing encodings.cp1250
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing ntpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing _locale
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing site
# destroy site
# cleanup[2] removing math
# cleanup[2] removing _datetime
# cleanup[2] removing datetime
# cleanup[2] removing warnings
# cleanup[2] removing itertools
# cleanup[2] removing _bisect
# cleanup[2] removing bisect
# destroy bisect
# cleanup[2] removing _sha512
# cleanup[2] removing _random
# cleanup[2] removing random
# cleanup[2] removing _operator
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing _heapq
# cleanup[2] removing heapq
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing collections
# destroy collections
# cleanup[2] removing _functools
# cleanup[2] removing functools
# destroy functools
# cleanup[2] removing types
# destroy types
# cleanup[2] removing contextlib
# cleanup[2] removing msvcrt
# cleanup[2] removing getpass
# cleanup[2] removing hhelper
# destroy hhelper
# cleanup[2] removing steghelper
# destroy steghelper
# destroy _datetime
# destroy _signal
# destroy _sitebuiltins
# destroy ntpath
# destroy _stat
# destroy genericpath
# destroy stat
# destroy _locale
# destroy datetime
# destroy random
# destroy time
# destroy getpass
# destroy math
# destroy _random
# destroy itertools
# destroy _bisect
# destroy _sha512
# destroy contextlib
# destroy io
# destroy os
# destroy warnings
# destroy msvcrt
# destroy abc
# destroy _collections_abc
# destroy heapq
# destroy _operator
# destroy _heapq
# destroy _collections
# destroy _abc
# destroy _functools
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping encodings.cp1250
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping winreg
# cleanup[3] wiping _weakref
# cleanup[3] wiping _thread
# cleanup[3] wiping nt
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping _frozen_importlib_external
# destroy io
# destroy nt
# destroy winreg
# destroy marshal
# cleanup[3] wiping _warnings
# cleanup[3] wiping _imp
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# destroy _imp
# destroy _thread
# destroy _warnings
# destroy _weakref
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy _frozen_importlib
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\hesam\Desktop\yanderifier-master\yanderify>`
```
Maybe this help idk :D
