### ISSUE TITLE
yanderify crashed?!

### ISSUE THREAD

**Issue by halouthere233** [dunnousername/yanderifier#24]
have no idea what's going on here

this is from the command line

Loading...
Unknown encoder 'libx264'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\plugins\ffmpeg.py", line 661, in _append_data
    self._proc.stdin.write(im.tostring())
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "yanderify.py", line 260, in worker_thread
    raise e
  File "yanderify.py", line 224, in worker_thread
    vid1.append_data(img_as_ubyte(resize(frame, size)))
  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\core\format.py", line 492, in append_data
    return self._append_data(im, total_meta)
  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\plugins\ffmpeg.py", line 666, in _append_data
    raise IOError(msg)
OSError: [Errno 22] Invalid argument

FFMPEG COMMAND:
D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\Library\bin\ffmpeg.exe -y -f rawvideo -vcodec rawvideo -s 256x256 -pix_fmt rgb24 -r 30.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -crf 25 -v warning D:\Users\User\Desktop\yanderifier-master\yanderify\tmp.mp4

FFMPEG STDERR OUTPUT:

this is from the actual program

Started Yanderify 3.0.6-alpha-0
Warning: This is not a stable release and should not be treated as such.
Disclaimer: CPU mode on low-end computers or most laptops generally will cause the system to lock-up.
We are not liable if you freeze your PC by refusing to listen to this advice.
Written by dunnousername#8672.
heavily inspired by windy's efforts
New video input path: D:/Users/User/Desktop/yanderifier-master/sample/bakamitai.mp4
New image input path: C:/Users/Chromata/Downloads/WhatsApp Image 2020-08-12 at 19.06.03.jpeg
New video output path: D:/Users/User/Desktop/da de.mp4
starting...
Reloading checkpoints...
Finished reloading checkpoints
Loading sources...
Sources loaded
===========================
This section contains the details the devs need to fix this issue.
If you are reporting a bug, please include this entire section.
If you leave out any of it, there is a good chance the devs will not be able to help.
Error: received a OSError at stage "predict".
Message: "[Errno 22] Invalid argument

FFMPEG COMMAND:
D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\Library\bin\ffmpeg.exe -y -f rawvideo -vcodec rawvideo -s 256x256 -pix_fmt rgb24 -r 30.00 -i - -an -vcodec libx264 -pix_fmt yuv420p -crf 25 -v warning D:\Users\User\Desktop\yanderifier-master\yanderify\tmp.mp4

FFMPEG STDERR OUTPUT:
"
Full traceback:
  File "yanderify.py", line 224, in worker_thread
    vid1.append_data(img_as_ubyte(resize(frame, size)))

  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\core\format.py", line 492, in append_data
    return self._append_data(im, total_meta)

  File "D:\Users\User\Desktop\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\plugins\ffmpeg.py", line 666, in _append_data
    raise IOError(msg)

<log>
cpu=0
</log>
<inputs>
D:/Users/User/Desktop/yanderifier-master/sample/bakamitai.mp4 {C:/Users/Chromata/Downloads/WhatsApp Image 2020-08-12 at 19.06.03.jpeg} {D:/Users/User/Desktop/da de.mp4}
</inputs>
This is the last line of the crash report section.
===========================
yanderify crashed!
some common problems:
- you have an AMD card. AMD cards are not supported in GPU mode for technical reasons. However, you can run in CPU mode, albeit much lower. Please read the disclaimer at the top about CPUs!
- you have an NVIDIA card, but there is either not enough VRAM or the card is too old. >=700-series cards with >=2GB dedicated VRAM should work fine
- you have a working card, but there is not enough available VRAM to run the deepfake process. Browsers commonly cause VRAM issues. If you have any games open, try closing them.
- one of the devs fucked up somewhere. if that is the case, make sure to submit the full crash report (you might have to scroll up!), otherwise we cannot help you!

intel core i3-6098p, gtx 1050 (2gb vram), 8gb of ram, anything else, just ask me

**Comment by memcpy1337** [comment]
same
