### ISSUE TITLE
yanderifier crashes when i tried to open it

### ISSUE THREAD

**Issue by HaedenVideos2** [dunnousername/yanderifier#27]
So I was using the latest version today. So I downloaded it. then opened it. It shows some messages then there was an error message then it crashed so quickly that I could not see the error message. can someone help, please!

**Comment by HaedenVideos2** [comment]
Error: received a OSError at stage "predict".
Message: "[Errno 22] Invalid argument

FFMPEG COMMAND:
D:\yanderifier-master\miniconda\envs\yanderify\Library\bin\ffmpeg.exe -y -f rawvideo -vcodec rawvideo -s 2576x1936 -pix_fmt rgb24 -r 29.97 -i - -an -vcodec libx264 -pix_fmt yuv420p -crf 25 -v warning D:\yanderifier-master\yanderify\tmp.mp4

FFMPEG STDERR OUTPUT:
"
Full traceback:
File "yanderify.py", line 221, in worker_thread
vid1.append_data(img_as_ubyte(resize(frame, size)))

File "D:\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\core\format.py", line 492, in append_data
return self._append_data(im, total_meta)

File "D:\yanderifier-master\miniconda\envs\yanderify\lib\site-packages\imageio\plugins\ffmpeg.py", line 666, in _append_data
raise IOError(msg)

cpu=0 {C:/Users/jayde/Pictures/Video Projects/dame da ne source.mp4} {C:/Users/jayde/Pictures/lachlan the cringe lord yasuo.jpg} {D:/Deepfakes/lachlan baka mitai.mp4}
HOW TO FIX!!!!!!!!!!!! IM WAITING!!!!!!!!

**Comment by ChunkyMilk12** [comment]
idk why this guy posted my error message, but they're probably different issues

**Comment by HaedenVideos2** [comment]
i saw the error message now

**Comment by HaedenVideos2** [comment]
its the same error message like yours

**Comment by SakizciAdam** [comment]
I got the message:

`
Traceback (most recent call last):
  File "yanderify.py", line 68, in <module>
  File "yanderify.py", line 64, in reload
  File "demo.py", line 40, in load_checkpoints
  File "torch/serialization.py", line 365, in load
    f = open(f,'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint.tar'
[14868] Failed to execute script yanderify
`

**Comment by MirrorReflection** [comment]
@SakizciAdam I have met the same problem.Have you solved it?

**Comment by SakizciAdam** [comment]
> @SakizciAdam I have met the same problem.Have you solved it?

Nope, Im trying to find what checkpoint.tar does

**Comment by MirrorReflection** [comment]
@SakizciAdam I have found the checkpoint.tar in releases.It's not included in the yanderify.zip

**Comment by SakizciAdam** [comment]
> @SakizciAdam I have found the checkpoint.tar in releases.It's not included in the yanderify.zip

Can you send the link please?
