### ISSUE TITLE
Failed a sanity check

### ISSUE THREAD

**Issue by bryanhjn** [dunnousername/yanderifier#38]
Failed a sanity check. You should tell the devs about this!
Traceback (most recent call last):
  File "install\postinstall.py", line 10, in <module>
    raise e
  File "install\postinstall.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by HenrijsS** [comment]
After installing numpy (using:)
`pip install numpy`

Runing the post-install again:

Failed a sanity check. You should tell the devs about this!
Traceback (most recent call last):
  File ".\postinstall.py", line 10, in <module>
    raise e
  File ".\postinstall.py", line 7, in <module>
    subprocess.check_output('ffmpeg -h')
  File "D:\Program Files (x86)\Python\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Program Files (x86)\Python\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files (x86)\Python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files (x86)\Python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by NPBeta** [comment]
lol this is **NOT** caused by numpy and you don't need to install dependencies yourself.
It is caused by an error **before it**: `CondaValueError: invalid package specification: x264=='1!152.20180717'`
This will cause the conda environment fail to create, so those dependencies won't install automatically.
Please comment or just simply delete the last line `- x264=='1!152.20180717'` in `environment.yml`, and run the installation again.
Note that this just a **temporary** fix, and may lead to x264 encoded videos fail to load.

**Comment by csrednicki** [comment]
I have the same error

**Comment by Animan8000** [comment]
@csrednicki What version of Yanderify are you using?

**Comment by csrednicki** [comment]
> @csrednicki What version of Yanderify are you using?

Latest, today I cloned repo

**Comment by Animan8000** [comment]
Umm, I hope it's not the repository files themselves. The main branch also is the really buggy v3 (a lot of people reported installation issues for v3). For official releases I recommend either [v4.0.3](https://github.com/dunnousername/yanderifier/releases/tag/v4.0.3-stable) or [2.0.5](https://github.com/dunnousername/yanderifier/releases/tag/v2.0.5) or if you got an RTX 3K card, then the new [v5](https://github.com/dunnousername/yanderifier/releases) alpha.

If you're looking for the source code specifically instead, like for the latest v4 version, it has it's [own branch](https://github.com/dunnousername/yanderifier/tree/latest-v4) with the code.

**Comment by xference** [comment]
@HenrijsS  So have you solve the errors you mentioned? I also meet the same, could you please deliver me the way!?

**Comment by Animan8000** [comment]
> @HenrijsS So have you solve the errors you mentioned? I also meet the same, could you please deliver me the way!?

You got this issue on a release or you downloaded the repo for changing the source code only?

**Comment by xference** [comment]
@Animan8000 just download the clone ZIP

**Comment by Animan8000** [comment]
> @Animan8000 just download the clone ZIP

I'm sorry for the late response. You wanna download a release I assume, not clone the repository (cloning is for messing with the source code and changing it. Also the main branch is outdated if you're interested into the source code only, [latest-v4](https://github.com/dunnousername/yanderifier/tree/latest-v4) is the newest branch if you're looking for that).

If you're using one of the new RTX 3K cards, then you probably wanna try the new [alpha](https://github.com/dunnousername/yanderifier/releases), otherwise I do recommend a version like [v4.0.3](https://github.com/dunnousername/yanderifier/releases/tag/v4.0.3-stable) (don't forget downloading the [checkpoint](https://github.com/dunnousername/yanderifier/releases/download/model/checkpoint.tar) for that version) or [v2.0.5](https://github.com/dunnousername/yanderifier/releases/tag/v2.0.5).
