### ISSUE TITLE
 This app won't work on your PC 

### ISSUE THREAD

**Issue by AlexZhu2001** [dunnousername/yanderifier#48]
This section contains the details the devs need to fix this issue.
If you are reporting a bug, please include this entire section.
If you leave out any of it, there is a good chance the devs will not be able to help.
Error: received a OSError at stage "predict".
Message: "Could not load meta information
=== stderr ===

ܾʡ"
Full traceback:
  File "yanderify.py", line 211, in worker_thread

  File "imageio\core\functions.py", line 129, in get_reader

  File "imageio\core\format.py", line 168, in get_reader

  File "imageio\core\format.py", line 217, in __init__

  File "imageio\plugins\ffmpeg.py", line 358, in _open

  File "imageio\plugins\ffmpeg.py", line 523, in _load_infos

<log>
cpu=0
</log>
<inputs>
D:/6.mp4 D:/source.jpg D:/dst.mp4
</inputs>
This is the last line of the crash report section.

Loading...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "yanderify.py", line 269, in worker_thread
  File "yanderify.py", line 211, in worker_thread
  File "imageio\core\functions.py", line 129, in get_reader
  File "imageio\core\format.py", line 168, in get_reader
  File "imageio\core\format.py", line 217, in __init__
  File "imageio\plugins\ffmpeg.py", line 358, in _open
  File "imageio\plugins\ffmpeg.py", line 523, in _load_infos
OSError: Could not load meta information
![图片](https://user-images.githubusercontent.com/23147652/95006281-6e63ce00-0635-11eb-93f0-3f1ec42bb797.png)
![图片](https://user-images.githubusercontent.com/23147652/95006288-8d626000-0635-11eb-8838-51045ac0db3c.png)

**Comment by AlexZhu2001** [comment]
I have solved this problem, which seems to be the ffmpeg used by imageio. I downloaded the latest ffmpeg and set the environment variable IMAGEIO_FFMPEG_EXE ，and problem is solved
