### ISSUE TITLE
three kinds of problems

### ISSUE THREAD

**Issue by Gezelli-z** [dunnousername/yanderifier#73]
First of all, I would like to know whether the following problems can be solved by myself or need you to compile the program fraudulently. I am very grateful.

This is the first one

Loading...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "yanderify.py", line 269, in worker_thread
  File "yanderify.py", line 211, in worker_thread
  File "imageio\core\functions.py", line 126, in get_reader
ValueError: Could not find a format to read the specified file in mode '?'

Second one
Loading...
Imageio: 'ffmpeg-win32-v3.2.4.exe' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error 【WinError 10053】 The software in your host aborted an established connection.>.
Error while fetching file: <urlopen error 【WinError 10053】 The software in your host aborted an established connection.>.

Third
Error while fetching file: <urlopen error 【Errno 11004】 getaddrinfo failed>.

Finally, how to solve the crash problem sometimes

Thanks

**Comment by Animan8000** [comment]
Hmm. For the second problem it's basically trying to download a particular FFmpeg client which did fail. For that particular case you can download this [ffmpeg-win32-v3.2.4.zip](https://github.com/dunnousername/yanderifier/files/6057798/ffmpeg-win32-v3.2.4.zip) and put the .exe file into `%LOCALAPPDATA%\imageio\ffmpeg`, so Yanderify will notice that the client is already on the PC and doesn't need to download it by itself. Good luck!

**Comment by Gezelli-z** [comment]
I have already understood the second question. I collected some people’s questions for help, but the first question still bothers me. I have tried to change the photo to jpg png format.Thanks

**Comment by Animan8000** [comment]
I'm not sure if this might be related to imageio FFmpeg. If you mean that the image cannot be loaded despite it being jpg/png. Because I remember once somebody claiming that the client can accidentally corrupt itself, if something goes wrong during the download, so the corrupted client needs to be removed and redownloaded/replaced.
