### ISSUE TITLE
yanderify crashed in CPU mode

### ISSUE THREAD

**Issue by Mosesofmason** [dunnousername/yanderifier#76]
The log shows:

```
This section contains the details the devs need to fix this issue.
If you are reporting a bug, please include this entire section.
If you leave out any of it, there is a good chance the devs will not be able to help.
Error: received a RuntimeError at stage "predict".
Message: "number of dims don't match in permute"
Full traceback:
  File "yanderify.py", line 229, in worker_thread

  File "yanderify.py", line 182, in make_animation_batch

<log>
cpu=1
</log>
<inputs>
C:/Users/aaa/Desktop/starlin.mp4 C:/Users/aaa/Desktop/s.jpg C:/Users/aaa/Desktop/s.mp4
</inputs>
```

The command window has this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "yanderify.py", line 269, in worker_thread
  File "yanderify.py", line 229, in worker_thread
  File "yanderify.py", line 182, in make_animation_batch
RuntimeError: number of dims don't match in permute
```

My CPU is i7-10700, I believe it is fast enough to run Yanderify?

**Comment by Animan8000** [comment]
What version of Yanderify did you use? If it's v4.0.3, try maybe v2.0.5 or the new alpha, in case that fixes it somehow.

**Comment by Mosesofmason** [comment]
Yes, the latest v5.0.0 alpha 1 works.
